export { detectContext } from "./lib/context.js";
export { VaultReader } from "./lib/reader.js";
export { VaultWriter } from "./lib/writer.js";
export { renderTemplate } from "./lib/templates.js";
export { interpolate } from "./lib/interpolate.js";
export { parseFrontmatter, serializeFrontmatter } from "./lib/frontmatter.js";
export { readFileOrNull, writeFileSafe, slugify, todayDate } from "./lib/fs-helpers.js";
export { icon, table, progressBar, box, section, statusIcon, stepLine, keyValue, divider } from "./lib/output.js";
export { detectStack, renderStackMarkdown } from "./lib/stack-detect.js";
export { detectConventions, renderConventionsMarkdown } from "./lib/conventions-detect.js";
export { AgentRegistry } from "./agents/registry.js";
export { AgentContextBuilder } from "./agents/context-builder.js";
export { parseAgentFile } from "./agents/loader.js";
export { TaskManager } from "./tasks/manager.js";
export { TaskTracker } from "./tasks/tracker.js";
export { WorkflowEngine } from "./workflow/engine.js";
export type { StepExecutor, GateChecker, WorkflowResolver } from "./workflow/engine.js";
export { WorkflowState } from "./workflow/state.js";
export { getBuiltinWorkflows, getBuiltinWorkflow } from "./workflow/builtin.js";
export { parseWorkflowYaml, loadCustomWorkflows } from "./workflow/loader.js";
export { McpServer } from "./mcp/server.js";
export { ToolHandlers } from "./mcp/handlers.js";
export { getToolDefinitions } from "./mcp/tools.js";
export { engramSearch, engramStore, engramJudge, formatEngramResults, EngramBridge, isEngramAvailable } from "./lib/engram.js";

export type { ProjectContext, VaultData, DailyLog, BranchContext } from "./lib/types.js";
export type { Frontmatter } from "./lib/frontmatter.js";
export type { AgentDefinition, PreparedAgent, AgentPermissions, VaultSection, GitOperation } from "./agents/types.js";
export type { Task, TaskStatus, TaskPriority, TaskFilter } from "./tasks/types.js";
export type { WorkflowDefinition, WorkflowRun, StepDefinition, WorkflowStatus, StepState, GateType } from "./workflow/types.js";
